import type { User, Post } from "./types"

export const mockUserData: User = {
  id: "1",
  name: "John Doe",
  bio: "Cultural enthusiast and photographer. I love documenting the traditions and heritage of North Cyprus.",
  profileImage: "/placeholder.svg?height=128&width=128&text=John",
  posts: 12,
  likes: 248,
  contributions: 15,
}

export const mockUserPosts: Post[] = [
  {
    id: "1",
    title: "Traditional Cypriot Pottery: A Dying Art",
    excerpt:
      "Exploring the ancient techniques of pottery making in North Cyprus and the artisans keeping the tradition alive.",
    content: "Full content here...",
    image: "/placeholder.svg?height=300&width=400&text=Pottery",
    category: "Arts",
    date: "2025-03-15",
    likes: 42,
    dislikes: 3,
    comments: 12,
  },
  {
    id: "2",
    title: "Mesaoria Plains: The Breadbasket of Cyprus",
    excerpt: "A photographic journey through the fertile plains that have fed the island for centuries.",
    content: "Full content here...",
    image: "/placeholder.svg?height=300&width=400&text=Plains",
    category: "History",
    date: "2025-02-28",
    likes: 36,
    dislikes: 1,
    comments: 8,
  },
  {
    id: "3",
    title: "Recipe: Authentic Cypriot Halloumi",
    excerpt: "Learn how to make traditional halloumi cheese using methods passed down through generations.",
    content: "Full content here...",
    image: "/placeholder.svg?height=300&width=400&text=Halloumi",
    category: "Recipes",
    date: "2025-02-10",
    likes: 89,
    dislikes: 2,
    comments: 24,
  },
  {
    id: "4",
    title: "The Folk Dances of North Cyprus",
    excerpt: "Documenting the traditional dances that tell stories of love, war, and daily life in Cypriot culture.",
    content: "Full content here...",
    image: "/placeholder.svg?height=300&width=400&text=Dance",
    category: "Folklore",
    date: "2025-01-22",
    likes: 51,
    dislikes: 0,
    comments: 15,
  },
  {
    id: "5",
    title: "The Ancient Olive Trees of Karpas",
    excerpt: "Some olive trees in the Karpas Peninsula are over 800 years old. Here's their story.",
    content: "Full content here...",
    image: "/placeholder.svg?height=300&width=400&text=Olive+Trees",
    category: "History",
    date: "2025-01-05",
    likes: 63,
    dislikes: 4,
    comments: 19,
  },
  {
    id: "6",
    title: "Traditional Instruments in Cypriot Music",
    excerpt: "From the zurna to the davul, these instruments have shaped the sound of Cyprus for centuries.",
    content: "Full content here...",
    image: "/placeholder.svg?height=300&width=400&text=Instruments",
    category: "Arts",
    date: "2024-12-18",
    likes: 47,
    dislikes: 2,
    comments: 11,
  },
]
